version: "3.1"
services:
  elasticsearch:
    restart: always #docker 启动这个容器也跟着启动
    image: elasticsearch:8.6.0 #容器名字对应版本好
    container_name: elasticsearch #容器的名称
    hostname: es-master
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - $PWD/es/data/:/usr/share/elasticsearch/data
      - $PWD/es/logs/:/usr/share/elasticsearch/logs/
      - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  # logstash:
  #   image: logstash:7.12.1
  #   container_name: logstash
  #   restart: always
  #   ports:
  #     - "5044:5044"
  #     - "9600:9600"
  #   environment:
  #     - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
  kibana:
    restart: always #docker 启动这个容器也跟着启动
    image: kibana:8.6.0 #容器名字对应版本好
    container_name: kibana #容器的名称
    ports:
      - "5601:5601"
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - $PWD/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch