version: "3.1"
services:
    elasticsearch:
      restart: always #docker 启动这个容器也跟着启动
      build:
        context: .
        dockerfile: Dockerfile
      container_name: elasticsearch #容器的名称
      hostname: es-master
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        - "discovery.type=single-node"
        - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      volumes:
        - $PWD/es/data/:/usr/share/elasticsearch/data
        - $PWD/es/logs/:/usr/share/elasticsearch/logs/
        - $PWD/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logstash:
      image: logstash:8.6.0
      container_name: logstash
      restart: always
      ports:
        - "5044:5044"
        - "9600:9600"
      environment:
        - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
      volumes:
        - $PWD/logstash/config/:/usr/share/logstash/config/
        - $PWD/logstash/pipeline/:/usr/share/logstash/pipeline/ 
        - $PWD/logstash/conf.d/:/usr/share/logstash/conf.d/
        - $PWD/logstash/log/:/usr/share/logstash/log/
        - $PWD/logstash/mysql-connector-java-5.1.49.jar:/usr/share/logstash/config/mysql-connector-java-5.1.49.jar
      depends_on:
        - elasticsearch
    kibana:
      restart: always #docker 启动这个容器也跟着启动
      image: kibana:8.6.0 #容器名字对应版本好
      container_name: kibana #容器的名称
      ports:
        - "5601:5601"
      environment:
        - "TZ=Asia/Shanghai"
      volumes:
        - $PWD/kibana.yml:/usr/share/kibana/config/kibana.yml
      depends_on:
        - elasticsearch
    db:
      image: mysql:5.7
      restart: always
      container_name: mysql #容器的名称
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: 123456
      volumes:
        - $PWD/mysql/db/:/var/lib/mysql/
        - $PWD/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf